shared/definition.go
=> shared: Set default variant

image/lxc.go
=> lxc: Remove "rootfs" prefix in tarball

README.md, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, generators/hostname_test.go, generators/hosts_test.go, image/lxc.go, image/lxc_test.go, image/lxd.go, image/lxd_test.go, shared/definition.go, shared/util.go, shared/util_test.go
Use the yaml tags instead of the struct names in the templates.
=> Use yaml tags in pongo2 templates

managers/yum.go, sources/centos-http.go
In order to create a usable image, we would also need to add a `post-unpack` action to the definition:
```yaml
actions:
- trigger: post-unpack
action: |-
#!/bin/sh
cd /mnt/cdrom/Packages
rpm -ivh --nodeps rpm-4.11.3-25.el7.x86_64.rpm
rpm -ivh --nodeps yum-3.4.3-154.el7.centos.noarch.rpm
mkdir -p /etc/yum.repos.d
cat <<- EOF > /etc/yum.repos.d/cdrom.repo
[cdrom]
name=Install CD-ROM
baseurl=file:///mnt/cdrom
enabled=0
gpgcheck=1
gpgkey=file:///mnt/cdrom/RPM-GPG-KEY-CentOS-7
EOF
yum --disablerepo=\* --enablerepo=cdrom -y reinstall yum
yum --disablerepo=\* --enablerepo=cdrom -y groupinstall "Minimal Install"
rm -rf /mnt/cdrom /etc/yum.repos.d/cdrom.repo
releases:
- 7
```
=> Fix CentOS

README.md
Link to Ubuntu YAML example was suffixed by an '.md' which does not
reflect content of the examples directory.
=> <fix/typo: Fix a typo a code documentation>

distrobuilder/main.go
Just have a PersistentPreRun hook for cobra isn't enough, because right
before the app.Execute() we call ioutil.TempDir, which tries to create a
new distrory under /var/cache, so it fails as bellow:
distrobuilder help
Failed to create cache directory: mkdir /var/cache/distrobuilder.685166231: permission denied
By moving the check for root user as the first thing distrobuilder does
solves the problem.
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
=> main.go: Check for root user as the first thing in main

shared/util_test.go
=> tests: Fix flaky GPG tests

doc/examples/archlinux
I tried building the archlinux example, but `lxc-start` failed due to `/sbin/init` being missing. I added `systemd-sysvcompat`, which provides `/sbin/init`, as a dependency.
=> Add systemd-sysvcompat as archlinux dependency

distrobuilder/main.go
Before this patch, if a user executes distrobuilder using the debian
example without having debootstrap installed, the following message is
returned:
Error: Error while downloading source: exec: "debootstrap": executable file not found in $PATH
Usage:
distrobuilder build-dir <filename|-> <target dir> [flags]
Flags:
-h, --help   help for build-dir
Global Flags:
--cache-dir   Cache directory
--cleanup     Clean up cache directory (default true)
-o, --options     Override options (list of key=value)
This happens because distrobuilder subcommands uses cobra's RunE or PreRunE,
so if an error is returned, the help message is shown.
In order to avoid this message, execute os.Exit(1) when downloader.Run fails:
Error: Error while downloading source: exec: "debootstrap": executable file not found …
=> main.go: Do not show help message if downloader.Run fails

README.md
The instructions show how to use `distrobuilder` to create a container image for Ubuntu, then use it to launch a container. 
The instructions emphasize the terminology `container image`, which I believe is a suitable for these images.
=> doc: Added usage instructions in Readme.md

shared/net.go, sources/alpine-http.go, sources/archlinux-http.go, sources/centos-http.go, sources/fedora-http.go, sources/gentoo.go, sources/ubuntu-http.go
This removes the functions `DownloadSha{256,512}` in favor of the more general function `DownloadHash` which let's you specify a hash function.
=> Export function DownloadHash

distrobuilder/chroot.go, distrobuilder/main.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, doc/examples/sabayon, doc/examples/sabayon-docker, managers/equo.go, managers/manager.go, shared/chroot.go, shared/definition.go, sources/alpine-http.go, sources/docker.go, sources/sabayon.go, sources/source.go
Features added:
* environment variables configuration from image files
* repositories handler
* docker http sourcer
=> Add sabayon support and new features

sources/archlinux-http.go
=> sources: Remove temporary root directory in Arch

sources/archlinux-http.go, sources/archlinux-http_test.go
If image.release is empty or not set, the latest release will be used.
This resolves #126.
=> sources: Get latest Arch Linux release by default

distrobuilder/main.go
=> main: Add --timeout flag

distrobuilder/chroot.go, doc/examples/plamolinux, managers/apk.go, managers/apt.go, managers/dnf.go, managers/equo.go, managers/manager.go, managers/pacman.go, managers/portage.go, managers/yum.go, managers/zypper.go, shared/definition.go, shared/definition_test.go, sources/plamolinux-http.go, sources/source.go
Plamo Linux uses multiple scripts for managing packages. This required some changes in the managers code, so now we can specify custom managers (see Plamo Linux example).
Package management itself still needs to be addressed here. It seems as though one would have to download every package manually and install it. This is somewhat cumbersome.
However, this creates an almost complete rootfs. The `tar` command used by `installpkg` won't install packages containing files with the sticky bit for example. This affects only three packages AFAICT. It shouldn't be a problem though since this issue would also exist in the current lxc-template which I assume is fine.
=> Add Plamo Linux

sources/opensuse-http.go
Use the same mirror for the actual image and the checksum file.
=> sources: Fix openSUSE mirror

sources/opensuse-http.go
=> sources: Fix openSUSE image verification

doc/examples/sabayon, doc/examples/sabayon-docker
* Enable systemd-networkd service
* Added ETP_NONINTERACTIVE for avoid
blocking installation processes
* Disable systemd-journald-audit service
Signed-off-by: Daniele Rondina <geaaru@sabayonlinux.org>
=> sabayon: Update examples

sources/docker.go
Fix use of docker-http source. With new API an object DownloadOpts is mandatory.
=> sources/docker-http: Fix SIGSEGV

doc/examples/openwrt, managers/manager.go, managers/opkg.go, shared/definition.go, sources/openwrt-http.go, sources/source.go
I'm trying to modify the distrobuilder to work with OpenWrt. I think I understood most parts of the process, however there are some corners I haven't figured out yet:
I'll continue to work on the missing bits but would be happy to get some comments if I'm on the wrong track.
=> opkg: add distro

README.md
=> doc: mention `go get ...` failure in README

shared/util.go
=> shared: Use RunCommandSplit for GPG

sources/opensuse-http.go
=> source: Provide fallback URL for openSUSE

generators/cloud-init.go, generators/cloud-init_test.go, generators/generators.go, generators/hosts.go
Make sure the cloud-init generator doesn't leave any files behind when
building an lxc image.
This depends on https://github.com/lxc/lxd/pull/6084
=> generators: Fix cloud-init

doc/examples/apertis, doc/source.md, shared/definition.go, sources/apertis-http.go, sources/source.go
Add the simple downloader and template for [Apertis OS](https://images.apertis.org/) -- Debian's derivative.
=> Add Apertis

distrobuilder/chroot.go, managers/zypper.go
Remove the special case of openSUSE 42.3 and the `--allow-downgrade`
flag. Since openSUSE 42.3 is EOL, we can drop support for it.
=> managers: Add --allow-downgrade to zypper

sources/openwrt-http.go
This fixes connectivity issues, and makes OpenWrt more usable.
The build.sh [1] script uses subversion which makes it a new dependency
of distrobuilder.
[1] https://github.com/mikma/lxd-openwrt
=> sources: Run OpenWrt correctly

doc/examples/ubuntu.yaml, doc/source.md
`apt_sources` was removed in https://github.com/lxc/distrobuilder/pull/246
Remove `apt_sources` from the docs and the Ubuntu example to avoid
confusion. Also include example use of the `sources.list` special-case
repository in the Ubuntu example.
=> Remove references to "apt_sources"

sources/openwrt-http.go, sources/openwrt-http_test.go
This removes the need of patching the build scripts with the `patch`
command.
=> sources: Fix OpenWrt

doc/examples/scheme.yaml, doc/packages.md
This cleans up the docs and the example scheme.yaml file for the
"custom-manager" option.
Signed-off-by: Eddy Gurney <github@eddyg.promessage.com>
=> Fix syntax in documentation for custom-manager

distrobuilder/chroot.go, distrobuilder/main.go
This enables rendering of source keys as well as repository keys.
This closed #258.
=> distrobuilder: Extend pongo2 template usage

distrobuilder/chroot.go, doc/examples/scheme.yaml, doc/packages.md, managers/manager.go, shared/definition.go
Optionally allow setting `flags` (for the `install` and `remove` actions) in package sets.
This can be used in situations where it is desirable to use `--no-install-recommends` when installing certain packages, as shown below.
-------
Example usage:
```
- packages:
- lightdm
action: install
flags:
- --no-install-recommends
```
=> Add support "flags" in package sets

doc/source.md, shared/definition.go
If a package set has the `early: true` option set, those packages are installed with the source (when using `debootstrap`). But because the early packages remain in the set of packages, they are attempted to be installed again.
This is a minor cosmetic issue, but not attempting to re-install the early packages makes the install log slightly cleaner.
Also remove references to the old `early_packages` option in the docs.
=> Don't attempt to re-install packages that were installed early

sources/alpine-http.go
When building the edge release, the same_as field is required for
downloading the source tarball and fixing the repo URLs.
This commit fixes the regex which is used to alter the apk repo file.
It now includes versions like 3.10 and above.
=> sources/alpine: Fix edge builds

sources/voidlinux-http.go
This updates the location of both sha256 and its signature file.
=> sources/void: Update location of checksums

sources/alpine-http.go
This fixes the regex which updates the repos for edge releases.
This fixes https://github.com/lxc/lxc-ci/issues/107.
=> sources/alpine: Fix regex

generators/lxd-agent.go
This fixes the location of the unit files as well as their permissions.
=> generators/lxd-agent: Fix systemd unit files

shared/chroot.go
This rbinds /dev in order for it to work in containers as well.
=> shared/chroot: Recursively bind /dev

image/lxd.go
This renames the resulting VM image to "disk.qcow2" if not unified.
=> image/lxd: Rename resulting VM image

shared/chroot.go
=> shared/chroot: Make /dev/fuse read-only

generators/lxd-agent.go
This checks the existance of /lib/systemd/system, and uses
/usr/lib/systemd/system if the former doesn't exist.
=> generator/lxd-agent: Fix systemd units path

distrobuilder/main.go, distrobuilder/main_lxd.go
This fixes an issue where the --vm flag would be ignored if running
build-lxd.
=> main: Fix build-lxd for VMs

distrobuilder/main.go, distrobuilder/main_build-dir.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, shared/definition.go, shared/definition_test.go
This changes the types filtering behaviour.
When running build-dir, only section with no types filter will be
processed.
=> shared: Differentiate between build-dir and others

distrobuilder/main_lxd.go, distrobuilder/vm.go, shared/chroot.go
Instead of bind-mounting /dev, it now creates necessary /dev files using
mknod. When creating VMs, it bind-mounts the loop device and its
partitions as well.
=> chroot: Don't bind-mount /dev

shared/definition.go
Early packages usually don't have a specific target and therefore should
have no value for that.
=> shared/definition: Fix early packages

distrobuilder/main_lxc.go, distrobuilder/main_lxd.go
Entries in the files section should always be considered if they have no
type filter specified.
=> main: Fix file generators

generators/lxd-agent.go
This is needed for it to successfully run on CentOS 7.
=> generators/lxd-agent: Add trans=virtio option

distrobuilder/main.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, shared/definition.go, shared/definition_test.go
This fixes build-{lxc,lxd} where it would fail to process sections with
no defined type filter.
This fixes #304.
=> main,shared: Fix undefined image target

shared/chroot.go
This creates /dev/shm in the chroot, and changes its file mode to 1777.
=> shared/chroot: Create /dev/shm

shared/util.go, shared/util_test.go
This fixes the Gentoo ppc64le checksum matching.
=> Fix checksum matching

shared/util.go
tar does not preserve xattrs by default, so update Pack and PackUpdate
to use the --xattrs flag. This avoids dropping the security.capability
xattr, which is used for binaries such as ping.
Downstream bug: https://crbug.com/1093811
Signed-off-by: Stephen Barber <smbarber@chromium.org>
=> shared/util: preserve xattrs in Pack/PackUpdate

doc/examples/ubuntu.yaml, doc/generators.md, generators/copy.go, generators/copy_test.go, generators/generators.go, shared/definition.go
Closes #110
Copy any file from the host to the container using "destination".
Logic is very similar to that one from Docker.
First check if the input is a file or a directory.
Then check whether the destination finishes in a "/" or not
Afterwards, the rules for copying can be applied
Rules for copying:
- If <src> is a directory, the entire contents of the directory
are copied. Only symlinks and regular files are supported.
Note 1: The directory itself is not copied, just its contents.
Note 2: For files copied, only regular unix permissions are kept
- If <src> is any other kind of file, it is copied individually
along with its metadata. In this case, if <dest> ends with a trailing
slash /, it will be considered a directory and the contents of <src>
will be written at <dest>/base(<src>).
- …
=> generators: Add copy generator

generators/hostname.go, generators/hosts.go
Signed-off-by: Get OpenDroplet <getopendroplet@gmail.com>
Was skipped definition from config file.
=> Added missing definitions in generators hosts, hostname

sources/docker.go
This permits to creation LXD image from a docker image pulled by a private docker registry with a username and a password.
Require master upstream of the docker-companion project.
=> sources/docker: Permit to use private docker registry with credentials

shared/definition.go, sources/rocky-http.go, sources/source.go
These are the files I've been working with locally to try and build a
Rock Linux LXD image. I've made every attempt to fix syntax and
eliminate branches that are not needed. Rocky exists only from 8.3 up,
so, using the centos-http.go as a reference, tried to create the
rocky-http.go. Could not test locally for /reasons/ not sure why. The
rocky.yaml file is based on the one that was issued by CentOS and then
modified as well. You may not wish to merge this (even if it is correct)
as I see that you don't normally do this with the .yaml files. Submitted
PR per Stéphane's request, after he helped me try to build locally.
=> Add Rocky Linux

shared/definition.go, sources/source.go, sources/springdalelinux-http.go
Since Sept 2020 we know that CentOS won't be a "production distribution" anymore.
While looking for an equivalent, I found Springdale Linux http://springdale.math.ias.edu/ which is doing the same thing as CentOS long before it.
This is the result of a try to get a working Springdale8 LXD image,
Please feel free to ask and tell, I need informations to get this working...
=> Add new distribution Springdale Linux

sources/almalinux-http.go
Changes:
* allow beta and RC ISOs downloads if stable images are not available.
* remove unsupported architecture armhfp code.
* use official AlmaLinux OS mirror for rootfs generation.
* use only BaseOS repository for rootfs generation.
I tested both LXC and LXD image builds for both x86_64 and aarch64 architectures with a config from that PR: https://github.com/lxc/lxc-ci/pull/305.
Currently, it will build aarch64 images from an AlmaLinux OS 8.4 beta ISO, but after a stable release it will pickup a stable ISO automatically.
=> AlmaLinux: clean up downloader code and add beta/rc images support

distrobuilder/main.go
=> main: Fix typo in systemd generator

sources/opensuse-http.go
=> sources/opensuse: Fix path to non-x86_64 tarballs

sources/opensuse-http.go
=> sources/opensuse: Fix URL to tarballs

distrobuilder/main.go
With `/run/systemd/system/network-device-down.service` in place and
NetworkManager installed, systemd-networkd brings up the networking and
assings an IP address, but then shortly after the inteface is brought
down by this service, breaking the network connection.
Add a `Before=systemd-networkd.service` dependency, to bring down the
interface before systemd-networkd is started and let it do it's thing
afterwards.
Fixes [LP: #1931088](https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1931088)
Related to https://github.com/lxc/distrobuilder/commit/aea15277f86a4a4bd4e3afcbc81105e4c6a7ca16
Signed-off-by: Lukas Märdian <slyon@ubuntu.com>
=> Avoid systemd generator to break systemd-networkd connections

sources/openwrt-http.go
Signed-off-by: Benjamin McGuire <benjamin@reelworks.net>
Due to changes in the filename, the Release Candidates are using the same naming for the rootfs image as the snapshots.
Tested on rc1 - rc3
=> Add ability to make Openwrt 21.02 images

distrobuilder/main.go
=> systemd: Fix typo in unit name

distrobuilder/main_repack-windows.go
- main: Remove duplicate defer statement
- main: Disable overlay on FUSE filesystems
=> windows: Disable overlay on FUSE filesystems

image/lxd.go
=> image: Fix unified LXD tarballs

sources/openwrt-http.go
OpenWrt seems to have removed support for verifying the checksum file
with gnupg.
=> sources/openwrt: Remove verification

distrobuilder/main_repack-windows.go
=> main: Support ISO generation with mkisofs

distrobuilder/main.go
=> main: Check systemd-sysctl path

sources/plamolinux-http.go
The path to the statically linked zstd command was not set, so I set.
In addition, Changed to prioritize host environment commands over
commands included in pkgtools8.
Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>
=> sources/plamolinux: more fix related to pkgtools8

distrobuilder/main_lxc.go
=> main: Fix post-files actions for lxc

distrobuilder/main_lxd.go
=> main: Check for snap when importing LXD image

distrobuilder/main_build-dir.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, doc/packages.md, doc/targets.md, generators/cloud-init.go, generators/cloud-init_test.go, generators/common.go, generators/copy_test.go, generators/dump.go, generators/dump_test.go, generators/generators.go, generators/generators_test.go, generators/hostname_test.go, generators/hosts_test.go, generators/template_test.go, shared/definition.go, shared/definition_test.go
This extends templating support to all generators. Source, Path,
and Content can be templated.
This resolves #550.
Note: This breaks backward compatability as some yaml keys are
renamed. That is because pongo2 doesn't support hyphens in key
names.
=> Extend templating support

doc/generators.md
- doc/generators: Add missing source field
- doc: Mention general pongo support
=> doc: Mention `source` key and general pongo2 support

sources/debootstrap.go
This enables merged /usr by default, and disables it for certain
distros/releases.
=> sources/debootstrap: Handle merged /usr

distrobuilder/main.go
PR #495 mentions that NoNewPrivileges needed to be deactivated
to fix systemd failures on alt/Sisyphus and Arch Linux. However,
on recent kernels (with fixes for [1] and [2]), NNP should work
properly inside containers.
1: https://bugs.launchpad.net/bugs/1839037
2: https://bugs.launchpad.net/bugs/1844186
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
=> main: remove NoNewPrivileges=no from systemd-generator

sources/rhel-common.go
This uses temporary directories for building RHEL based images as the
previous directory names caused the rootfs to be larger than needed.
This fixes #576.
=> sources: Fix RHEL common build directories

generators/cloud-init.go, generators/cloud-init_test.go
=> generators: Use new cloud-init config keys

managers/manager.go
=> managers: Add missing context to struct

generators/cloud-init.go, generators/cloud-init_test.go
This fixes a bug where cloud-init.network-config wouldn't be used if it
was set.
=> generators/cloud-init: Fix network-config

distrobuilder/main.go
On Gentoo, udevadm is located in /bin.
=> systemd-generator: Handle /bin/udevadm

distrobuilder/main.go
This is related to:
https://github.com/lxc/lxc/issues/4052
https://discuss.linuxcontainers.org/t/hardened-service-fails-to-start/13118
ProcSubset requires the subset= option on procfs and so requires a
dedicated proc mount which isn't allowed in our containers outside of
/proc itself. As a result, this one should be overriden.
=> systemd: Add override for ProcSubset

generators/lxd-agent.go
This prevents the following during shutdown (`journalctl -b-1 --grep lxd`):
```
Mar 21 21:03:17 foo systemd[1]: Unmounting /run/lxd_agent...
Mar 21 21:03:17 foo umount[487]: umount: /run/lxd_agent: target is busy.
Mar 21 21:03:17 foo systemd[1]: run-lxd_agent.mount: Mount process exited, code=exited, status=32/n/a
Mar 21 21:03:17 foo systemd[1]: Failed unmounting /run/lxd_agent.
```
This is related to https://github.com/lxc/lxd/pull/10098
=> lxd-agent: cleaner shutdown sequence

distrobuilder/main_repack-windows.go
Recent virtio ISOs contain drivers for Windows 11 and Windows Server
2022. There's no need to fall back on w10 and wk19 drivers
respectively.
=> windows: Use available w11 and 2k22 drivers

generators/lxd-agent.go
This reverts commit b94de08dc7822730267a403055d4bddf44ac3301.
This fixes regressions of lxd-agent on multiple systemd versions.
Closes https://github.com/lxc/lxc-ci/issues/480
=> Revert "lxd-agent: cleaner shutdown sequence"

distrobuilder/vm.go
Enable the following mount options on VM rootfs:
btrfs: nobarrier,commit=300,noatime
ext4: nobarrier,commit=300,noatime,data=writeback
Those are normally not recommended but for distrobuilder, it
make sense to have everything copied over as fast as possible
and then persisted properly to disk. We don't care about crash
consistency/fs recovery when building an image.
I used those options when building my own images (before
distrobuilder what a thing) and they allowed faster copying.
=> vm: Optimise mount options for speed

distrobuilder/main_lxd.go
This fixes an issue where the image target would ignore
`ImageTargetAll` when building LXD images.
=> main: Fix image targets for LXD

sources/funtoo-http.go, sources/opensuse-http.go, sources/openwrt-http.go
=> source: Return error correctly

distrobuilder/main.go
Distrobuilder creates a systemd generator (`/etc/systemd/system-generators/lxc`) to, among other things, work around problems with broken name space support inside containers.
Many of the distro images built by distrobuilder come with systemd. Those often ship multiple systemd units leveraging hardening features that rely on mount name spaces. The problem is that mount name spaces do not work well inside containers so the workaround so far has been to disable those features to avoid causing service failures.
This PR proposes to be more selective and only disable those hardening features relying on mount name spaces when `security.nesting=false`.
This was tested on a Focal host with kernel 5.13, LXD 5.0.0-e478009 rev 22894 and the following containers:
|Distro|Priv|Nesting|
|:-:|:-:|:-:| …
=> main: override systemd features only when security.nesting=false

distrobuilder/main.go, distrobuilder/main_validate.go, shared/definition.go, shared/definition_test.go
This adds some more template validation, including a new `validate` sub-command which validates a given template.
This resolves #614.
=> Add template validation

shared/definition.go
This fixes a bug where filter types would always be an empty array.
=> shared/definition: Fix unmarshalling of DefinitionFilterType

shared/version/version.go
=> shared/version: Bump version to 2.1

distrobuilder/main.go
- udev: Allow NetworkManager to manage veth interfaces
- main: Stop doing terrible things to NetworkManager
- main: Restrict veth rule to udev systems only
This supersedes #602.
=> Remove a handful of NetworkManager hacks

distrobuilder/main.go
We can get a small speed boost by using the C locale since we are
handling ASCII only anyway.
This saves between 1 and 3 million cycles in my `perf stat` tests
out of 16 to 36 million cycles.
=> main: export LC_ALL=C

doc/examples/sabayon.yaml, doc/examples/scheme.yaml, doc/examples/ubuntu.yaml
=> doc/examples: Fix typos in examples

sources/centos-http.go
- sources/centos: Disable fastestmirror plugin
- sources/centos: Use baseurl instead of metalink for repos
=> CentOS mirror updates

sources/opensuse-http.go
=> sources/opensuse: Change URL path to Leap images

sources/rhel-common.go, sources/rocky-http.go
- sources/rhel: Check directory before listing its entries
- sources/rocky: Fix gpg key and mirrorlist for v9
=> Fixes for Rocky Linux 9

distrobuilder/main.go
This masks the systemd-binfmt.service as it fails for containers.
=> systemd: Mask systemd-binfmt.service

sources/openeuler-http.go, sources/openeuler-http_test.go
Change the release style which the openEuler duplicates in both name and release
Signed-off-by: Li Chaoran <pkwarcraft@gmail.com>
=> change release style to 22.03-LTS-SPx

sources/common.go
OpenEuler will return HTTP 403 if the user-agent string is empty.
This sets the user-agent string to `distrobuilder` which fixes the
issue.
=> sources: Set user-agent for downloads

distrobuilder/main.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, doc/building.md, image/lxd.go, shared/util.go, shared/util_test.go
Allow specifying compression levels when the underlying tool or mksquashfs understands it. For example, gzip-1 or zstd-22. Compression levels are checked pre-run.
Signed-off-by: James Ye <jamesye@google.com>
=> image,shared: Allow specifying compression level

distrobuilder/main.go, sources/openeuler-http_test.go
This logs the error when the main command fails. We've been seeing failures for no apparent reason, so this might help find the issue.
=> main: Log error when main command fails

distrobuilder/main.go
This ensures that the error message of the main command is always logged
even if the logger itself is not configured. In this case, the error
will be printed to stderr.
=> main: Ensure main error is logged

sources/funtoo-http.go
Funtoo at the moment has two major releases:
- 1.4-prime
- next
This PR permits adding support to both releases.
Attention: merge this PR with the other PR to lxc-ci repository incoming
=> funtoo-http: Add support to next release

.sphinx/_templates/footer.html
There's no GitHub source for pages that are generated.
This should fix the link checker on the website.
=> doc: only include GitHub link in the footer for actual pages

README.md
Doc link to use.md is broken. I suspect doc/howto/build.md is the right target.
=> Fix broken link to use.md

doc/reference/actions.md
In #600 you can read that the `post-files`-hook is only executed for certain commandos. I think this is worth to be documented.
=> doc: Update actions regards to the hook post-files

distrobuilder/main_build-dir.go, doc/howto/build.md
This adds the `--with-post-files` flag to the `build-dir` command. If set, it runs those `post-files` actions which don't have a `type` filter set.
=> Add `--with-post-files` flag to `build-dir` command

distrobuilder/main_repack-windows.go, distrobuilder/main_repack-windows_test.go
Virtio drivers are built for both amd64 and arm64.
This tries extracting the architecture from the filename, and use the
appropriate virtio drivers.
Fixes #705
=> windows: Detect Windows architecture from filename

doc/examples/scheme.yaml, doc/reference/generators.md, generators/cloud-init.go, generators/cloud-init_test.go, generators/lxd-agent.go, shared/definition.go
AFAIK, upstart was used by CentOS before 7 and Ubuntu before 15.10. According to https://en.wikipedia.org/wiki/Upstart_(software) only ChromeOS and ChromiumOS are still using upstart but those are not something distrobuilder support building.
=> Drop support for upstart (no longer used)

doc/howto/build.md, doc/tutorials/use.md
Add the content from https://linuxcontainers.org/lxd/advanced-guide/ that was missing in the tutorial.
I did a little bit of cleanup as well, but no overhaul of the tutorial.
=> doc: add missing content for the tutorial

distrobuilder/main.go
Only allow masking units actually created by the lxc system-generator.
Currently, this is only network-device-down.service.
Fixes #739
=> lxd-generator: Fix masking units created by generator

doc/examples/scheme.yaml, doc/reference/source.md, shared/definition.go, sources/debootstrap.go
This is important for derivatives that can't be built with the main component alone, e.g., Astra Linux.
This allows to specify other components.
=> definition: Add Source.Components

distrobuilder/main.go, distrobuilder/main_build-dir.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, managers/manager.go, shared/definition.go, shared/definition_test.go
=> Restructure filtering and add new filters

distrobuilder/main.go, distrobuilder/main_build-dir.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, managers/manager.go, shared/definition.go, shared/definition_test.go
Revert the commits in https://github.com/lxc/distrobuilder/pull/744 .
That PR causes meta.tar.xz to lack the config.* and templates files, breaking 'lxc-create -t download'.
=> 2023 07 08/revert filters

distrobuilder/main.go, distrobuilder/main_build-dir.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, managers/manager.go, shared/definition.go, shared/definition_test.go
This is essentially the same as PR #744 but fixes LXC target filtering.
=> Restructure filtering and add new filters (v2)

distrobuilder/main.go, distrobuilder/main_build-dir.go, distrobuilder/main_lxc.go, distrobuilder/main_lxd.go, managers/manager.go, shared/definition.go, shared/definition_test.go
This reverts the recent filtering changes, as it has lead to broken images. Also, filtering behaviour seems inconsistent within distrobuilder so doing it at only one stage doesn't quite work.
=> Revert recent filtering

distrobuilder/main_repack-windows.go
Windows ISOs need to be mounted as UDF now otherwise no content will be
shown.
Signed-off-by: Thomas Hipp <thomashipp@gmail.com>
=> windows: Mount Windows ISO as UDF instead of ISO9660

distrobuilder/main.go
Do not bring the networking down on container startup when using routed nic together with NetworkManager, as in this case networking is configured externally by lxd. 
Signed-off-by: Aleksandar Ivanisevic <aleksandar@ivanisevic.de>
=> systemd: Don't bring network down when using routed networking

generators/lxd-agent.go
On some systems it appears we only get an action==CHANGE event which then prevents the normal rule for action==ADD to trigger.
This separates the RUN part to be run whenever udev sees something happening with the device but keeping the symlink generation to happen only on ADD.
=> udev: Trigger lxd-agent even on change events

distrobuilder/main.go
Without that older privileged containers may cause the subshell to return 1 causing the whole generator to exit due to it running under -eu.
=> systemd: Make sure subshell returns success

doc/reference/packages.md, managers/manager.go, managers/slackpkg.go, shared/definition.go, shared/osarch.go, sources/slackware-http.go, sources/source.go
- added http source (works with 15.0 and current)
- added slackpkg manager (upgrade/clean fail if there are not any packages to upgrade/clean)
=> Add support for slackware

managers/yum.go, shared/definition.go, sources/rpmbootstrap.go, sources/source.go
`rpmbootstrap` source is similar with `debootstrap` source in deb package system, but it's targeted in the rpm package system. Comparing with `centos-http`, `openeuler-http` sources, it's faster with less bandwidth using.
=> Added rpmbootstrap source

sources/openwrt-http.go
I noticed that the jenkins build failed...
1) For x64, the original #773 should already have resulted in using the correct download link for 23.x branch. The only explanation I can think of is that the Jenkins server only had the lxc/lxc-ci#789 but not yet the distrobuilder update, causing the script to select the "*-generic*" file naming convention. Anyway, this update includes some further code cleanup since actually none of the current release generations use the -generic file naming any more.
2) For arm64, I had neglected to look through the code carefully, sorry. Specifically, the directory structure of 23.x matches that of snapshot for ARM. Since future builds will retain this, I updated the code to make this the default.
=> Some fixes for 23.x OpenWRT

sources/openwrt-http.go
Somehow I got my notes on file (not just folder) naming conventions mixed up for ARM, which in 23.x matches snapshot (i.e., "default" is only for legacy, no-default naming becomes the standard now)... This should really be it now, though
=> Bugfix in openwrt-http.go to handle 23.x ARM release

sources/openwrt-http_test.go
Not that this can catch all that many errors to begin with, but non of the release branches referenced here are in use any more, so right now it's not doing anything at all. This should bring back the basic sanity check
=> Openwrt test script fix for 21-23.x branches

distrobuilder/main.go
When app.Execute() fails, there's no way of knowing which command
failed. However, we want to know this as we call postRun in case of an
error, and handle the "validate" subcommand differently in that
function.
This commit adds a subCommand field to the global struct which is used
to keep track of the current subcommand.
=> main: Keep track of current subcommand

distrobuilder/main_validate.go
If validation fails, the error message is printed twice. Setting
`SilenceErrors` to true leaves us with a single error message.
=> main_validate: Set SinceErrors to true

shared/osarch.go
This adds the missing x86_64 architecture to the Alpine Linux
architecture map.
=> shared/osarch: Add x86_64 to Alpine architecture map

go.mod, go.sum, sources/vyos-http.go
Changed because the download location for the Vyos Rolling update ISO file has changed.
This is a rewritten PR because I couldn't put together a commit in #789.
=> Update Vyos rolling update iso url

distrobuilder/main_incus.go
This adds the missing `--sources-dir` flag to the `build-incus`
subcommand.
Fixes #802
=> main: Add missing `--sources-dir` to `build-incus` command

distrobuilder/lxc.generator
I bundled lxc.generator in https://salsa.debian.org/freexian-team/debusine/-/merge_requests/545 and code-review turned up some suggestions for improvement.
=> Tidy up lxc.generator a bit

generators/cloud-init_test.go, generators/copy_test.go, generators/dump_test.go, generators/hostname_test.go, generators/hosts_test.go, generators/template_test.go, image/incus_test.go, image/lxc_test.go
This makes use of `os.MkdirTemp` in order to avoid race issues when
running the tests in parallel.
Closes #818
=> Remove race in tests

distrobuilder/main_incus.go, distrobuilder/main_repack-windows.go, distrobuilder/vm.go, generators/cloud-init.go, managers/pacman.go, shared/definition.go, shared/util.go, sources/debootstrap.go, sources/plamolinux-http.go, sources/slackware-http.go
Mirror what was done in lxc/incus#527 to fix build failure with incus >= 0.7.
=> Replace util.ValueInSlice with slices.Contains

distrobuilder/main_incus.go, distrobuilder/vm.go, shared/util.go
The root partition may not be /dev/sda2, for example if set the boot disk as the second disk, the root partition device name will be /dev/sdb2. It may be /dev/vda2 if not using san disk. The fix figured out the root partition device UUID and set the UUID as the root, the root partition device UUID keeps no change.
=> Fixed hardcoded root partition device name sda2

Makefile
The option `--exit-on-error' exists only on debian run-parts version. On centos, redhat or federa, run-parts has no such option.
The fix checks version and adds options accordingly.
=> Make run-parts running compatible with different versions

distrobuilder/main_repack-windows.go
And make the usage of drivers, windows-version, windows-arch understandable
=> Set repack-windows drivers default value

distrobuilder/lxc.generator
After #849, privileged Debian sid containers with systemd v256~rc3 work fine, but unprivileged ones don't. Adding the `ImportCredential=` override for them as well finally makes all my sid containers happy again.
=> systemd v256 seems to require overriding ImportCredential= for all containers

sources/utils.go
So ditrobuiler can be used to build the images with gpg fingerprint setting behind a firewall.
=> Support http-proxy keyserver options for gpg recv-keys

.sphinx/wordlist.txt, README.md, distrobuilder/lxc.generator, distrobuilder/main.go, distrobuilder/main_incus.go, doc/tutorials/use.md, generators/generators.go, generators/incus-agent.go
As the transition period for the image server has now expired, there's no point in keeping around this untested logic.
=> distrobuilder: Remove LXD support

distrobuilder/main_repack-windows.go, shared/util.go, shared/util_test.go
Driver like vioinput has multiple sys files `viohidkmdf.sys` and `vioinput.sys`, without `vioinput.sys` copied, the vioinput driver not work correctly.
The fix add the multiple files copied back.
=> Fixed multiple sys files not copied issue

Makefile
Since distrobuilder should run via root.
=> Run unit tests via sudo

sources/debootstrap.go
This logic is confusing/outdated and newer debootstrap should be able to cope out of the box. So let's remove it for now and we'll add back specific exceptions if needed.
=> debootstrap: Remove no-merged-usr/merged-usr logic

distrobuilder/main_repack-windows.go
This solves https://github.com/lxc/distrobuilder/issues/878
If it cant find WIM it tries ESD.
I also removed extension trimming in logging so there is difference between .wim and .esd
For now I only came across install.esd but I also added boot.esd check in case Microsoft starts packing it this way.
Repacking ISO with ESD takes longer because it has to deal with compression.
Installing Windows also works (tested in VM), maybe slower because of compression.
=> Add handling of ESD files for Windows repacking

distrobuilder/main_repack-windows.go
This fixes two issues when injecting drivers into an installed Windows 11 24H2 system:
* Adjust name of driver inf files
* Also install exes when injecting drivers
=> Fixes for Windows 11 24H2 driver injection

sources/opensuse-http.go
According to https://status.opensuse.org, mirrorcache-us.opensuse.org has been down for maintenance for 15 days. mirrorcache-eu.opensuse.org is still up, so switch temporarily to fix distrobuilder downloads.
=> opensuse: Temporarily switch to mirrorcache-eu to fix downloads

sources/nixos-http.go
Not quite ready to remove 24.05, but 24.11 and moving forward is an Incus specific image. Should have written it this way to begin with, but oh well. :)
=> nixos: correctly handle 24.11

distrobuilder/lxc.generator
Making /proc/sys read-only prevents networkd from changing some sysctls, let's see if just making /sys read-only is enough to keep things behaving.
Closes: https://github.com/lxc/incus/issues/1574
=> systemd: Relax read-only path workaround

.github/workflows/builds.yml
upload-artifact@v3 deprecated as of Jan 30. May require additional code updates elsewhere, though?
=> Update builds.yml to v4 artifact actions

sources/openwrt-http.go, sources/openwrt-http_test.go
Not much to add beyond title; concurrent commit in lxc-ci also available lxc/lxc-ci#870
=> Update OpenWRT to support v24.10 (and drop v21.x)

windows/repack_util.go
Closes https://github.com/lxc/distrobuilder/issues/900
Naming of INF files will be taken from original .inf files in virtio drivers folders and prefix added.
Example: `oem-vioscsi.inf`
=> Change naming of INF files

doc/reference/source.md, shared/definition.go, sources/alpaquita-http.go, sources/source.go
This PR adds miniroot downloader for Alpaquita Linux, a trimmed down Alpine derivative that supports (separately) both musl and glibc versions.  It's primarily targeted as a container delivery vehicle for BellSoft's [Liberica JDK](https://bell-sw.com/libericajdk/)
- https://bell-sw.com/alpaquita-linux/
- https://github.com/bell-sw/alpaquita-aports
I hope I have correctly inferred what this module has to do.  One thing I'm not entirely sure about is the place to normalize the variant from the implicit "default" into explicit "musl", so that variant can be omitted in image, but listed as "musl" (vs. "glibc") in filters further down the yaml config.  Feedback/guidance is appreciated.
As far as I understand, the architecture mappings are not required if the architecture naming is the same as …
=> sources: Add Alpaquita downloader

distrobuilder/main_incus.go, distrobuilder/passwd.go, shared/logger.go
This PR introduces two quality-of-life improvements:
- Enables `EnvironmentOverrideColors` flag in the log formatter
- Allows forcing colored log output in non-TTY sessions using `CLICOLOR_FORCE=1`
- Improves log readability in CI/CD pipelines and redirected outputs
- Adds support for using symbolic names (like `nginx`) instead of numeric UIDs/GIDs in file definitions
- Automatically resolves symbolic names to appropriate numeric IDs during build
- Solves the issue of varying UIDs/GIDs across different builds and environments
Example usage:
```yaml
files:
- generator: dump
path: /tmp/test
content: |-
hello
world
mode: "644"
uid: nginx
gid: nginx
```
- More maintainable configuration files
- Reduced errors from hardcoded numeric IDs
- Better portability across different environments
- More …
=> User/Group Name Resolution and Enhanced Color Logging

managers/apk.go
Not sure it it would have been better off as a feature request issue.  Since I have a proposed patch, a draft PR seemed more expedient.  Easy to file an issue retroactively if the procedure requires one.
This patch makes `apk` manager write `packages.repositories[].key` to `/etc/apk/keys/$name` if `name` is set.
Silently ignore entries that don't set both the name and the key so that existing configs that (ab)use (previously ignored) name as a comment don't break suddenly.
`url` and `name`+`key` are handled independently of each other, so you can combine them or keep them separate (one key for several repos) as necessary.
This allows for stuff like:
```yaml
packages:
manager: apk
repositories:
- url: https://localhost:8088/packages/user
name: user-badc0ffe.rsa.pub
key: |-
-----BEGIN …
```
=> managers/apk: Support packages.repositories[].key

README.md
Current dependencies contain `libguestfs-tools` which is quite a big package with many tools.
If Distrobuilder only needs `hivexregedit` command its provided for Debian/Ubuntu by separate package `libwin-hivex-perl`.
`libwin-hivex-perl` is also linked as provider in manpages for `hivexregedit` command: https://manpages.ubuntu.com/manpages/noble/man1/hivexregedit.1.html
=> Replace libguestfs-tools with libwin-hivex-perl

sources/alpaquita-http.go
The `image.variant` is an arbitrary user choice (e.g. an image that includes cloud-init), while possible `source.variant` values are predefined by the distro (e.g. libc, as is the case with Alpaquita).
Unfortunately parts of distrobuilder code base are confused about this, so I followed the wrong example when I first wrote this code.
See #916: "_`source.variant` vs `image.variant` confusion_" for more details.
=> sources: Alpaquita - use source.variant not image.variant

doc/tutorials/use.md
> When creating a Windows virtual machine, make sure to set the image.os property to something starting with Windows. Doing so will tell Incus to expect Windows to be running inside of the virtual machine and to tweak behavior accordingly.
>
> This notably will cause:
> - Some unsupported virtual devices to be disabled
> - The RTC clock to be based on system local time rather than UTC
> - IOMMU handling to switch to an Intel IOMMU controller
See <https://linuxcontainers.org/incus/docs/main/howto/instances_create/#launch-a-vm-that-boots-from-an-iso>
Also we could update the doc for Windows 11 installation.
We can avoid the `security.secureboot=false` and meet [minimal requirements](https://aka.ms/WindowsSysReq):
- 2 CPU
- 4GiB RAM
- 64GiB disk
- TPM device
Tested yesterday and it seems to …
=> Usage: Set image.os for Windows installation

sources/utils_test.go
Need to remove `gpgDir` after the test so that no gpg-agent processes are left behind loitering.
=> utils_test.go: TestRecvGPGKeys add missing cleanup
