- managers/pacman.go
> managers: add 'pacman' prefix to functions

- shared/definition.go
- shared/definition_test.go
> shared: do not require release field

- distrobuilder/main.go
> distrobuilder: fix missing arch

- managers/apt.go
> managers: update apt flags

- Makefile
- distrobuilder/chroot.go
- distrobuilder/main.go
- managers/pacman.go
- shared/util_test.go
- sources/debootstrap.go
> Various fixes and tweaks

- distrobuilder/main.go
- shared/util.go
> *: Remove init() code

- distrobuilder/chroot.go
> chroot: Fix mount logic and symlink handling

- distrobuilder/main.go
- generators/generators.go
- generators/hostname.go
- generators/hosts.go
- image/lxc.go
- image/lxd.go
- shared/util.go
> Add file generators and add lxc and lxd image output

- .travis.yml
- image/lxc.go
- image/lxc_test.go
- image/lxd.go
- image/lxd_test.go
> Add missing tests for lxc/lxd image generation

- distrobuilder/main.go
- shared/definition.go
- shared/definition_test.go
- shared/util.go
- shared/util_test.go
- sources/alpine-http.go
- sources/archlinux-http.go
- sources/centos-http.go
- sources/debootstrap.go
- sources/source.go
- sources/ubuntu-http.go
> Extend GPG support and add Suite option to Source

- image/lxc.go
- image/lxd_test.go
> image: Convert int to string properly

- generators/generators.go
- generators/hostname.go
- image/image.go
- image/lxc.go
- image/lxd.go
- image/lxd_test.go
- sources/alpine-http.go
- sources/archlinux-http.go
- sources/ubuntu-http.go
> *: Fix imports

- distrobuilder/main.go
- distrobuilder/main_build-dir.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- generators/hostname_test.go
- generators/hosts_test.go
- image/lxc.go
- image/lxc_test.go
- image/lxd.go
- image/lxd_test.go
> *: Switch to cobra CLI

- shared/util.go
- sources/debootstrap.go
> debootstrap: Support both gpg1 and gpg2

- shared/util.go
- shared/util_test.go
- sources/debootstrap.go
> shared: Fix GPG

- distrobuilder/main.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- generators/generators.go
- generators/generators_test.go
- generators/hostname.go
- generators/hostname_test.go
- generators/hosts.go
- generators/hosts_test.go
- image/lxc.go
- image/lxd.go
- image/lxd_test.go
- shared/util.go
- sources/alpine-http.go
- sources/archlinux-http.go
- sources/centos-http.go
- sources/debootstrap.go
- sources/ubuntu-http.go
Don't create a rootfs directory inside of the provided source directory. This PR also comes with a working compression flag for LXD.
> Use proper source directory

- shared/util.go
> shared: Make debootstrap noninteractive

- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- generators/dump.go
- generators/dump_test.go
- generators/generators.go
- generators/hostname.go
- generators/hostname_test.go
- generators/hosts.go
- generators/hosts_test.go
- generators/remove.go
- shared/definition.go
> Add more generators

- distrobuilder/chroot.go
- distrobuilder/main.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- shared/util.go
> distrobuilder: Add actions

- sources/alpine-http.go
- sources/archlinux-http.go
- sources/centos-http.go
- sources/ubuntu-http.go
> sources: Require GPG keys for HTTP downloads

- distrobuilder/chroot.go
- shared/util.go
- shared/util_test.go
> shared,chroot: Set environment variables

- shared/definition.go
> definition: Remove default for source.Variant

- distrobuilder/main_build-dir.go
- generators/dump.go
- generators/generators.go
- generators/hostname.go
- generators/hosts.go
- generators/remove.go
> generators: Extend generators by Run() command

- sources/debootstrap.go
> debootstrap: Fix GPG dir removal

- distrobuilder/main_build-dir.go
- generators/dump.go
- generators/dump_test.go
> *: Fix minor issues

- shared/definition.go
- shared/definition_test.go
> validate definition

- distrobuilder/main.go
- generators/hostname.go
- generators/hostname_test.go
- generators/hosts.go
- generators/hosts_test.go
> Improve /etc/hosts generator

- distrobuilder/main.go
> main: Remove rootfsDir variable

- README.md
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
> README: add useable yaml example

- shared/definition.go
> definition: Fix default values for name and description

- shared/definition.go
- shared/definition_test.go
> definition: Use kernel architecture name

- generators/hosts.go
> generator: Also prepend host entry on LXD

- distrobuilder/main.go
- shared/definition.go
- shared/definition_test.go
> *: Support yaml override on the command line

- distrobuilder/main.go
- generators/dump.go
- image/lxc.go
- shared/definition.go
- sources/alpine-http.go
- sources/archlinux-http.go
- sources/centos-http.go
- sources/debootstrap.go
- sources/source.go
- sources/ubuntu-http.go
> New line handling and templating

- distrobuilder/main.go
> main: Support multiple instances

- shared/definition.go
> definition: Use mapped architecture in name/description

- shared/definition.go
> definition: Fix typo

- distrobuilder/main.go
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
> main.go: Change Fprintf to Fprintln

- shared/definition.go
> definition: Fix default name and definition template

- sources/archlinux-http.go
> sources: Fix Arch Linux rootfs

- shared/definition.go
- sources/debootstrap.go
> Split source.Suite and source.SameAs

- generators/template.go
- generators/template_test.go
> generators: Append empty line to template files

- doc/examples/centos
- sources/centos-http.go
This partly addresses the issues in #102
> Fix CentOS 7

- doc/examples/centos
- sources/centos-http.go
This partly addresses the issues in #102.
> doc,sources: Fix CentOS 6

- generators/dump_test.go
- generators/generators_test.go
- generators/hostname_test.go
- generators/hosts_test.go
- generators/template_test.go
- image/lxc_test.go
- image/lxd_test.go
- shared/definition_test.go
- shared/osarch_test.go
- shared/util_test.go
> tests: Use testify

- sources/centos-http.go
> centos: Fix checksum file name

- doc/examples/centos
- doc/examples/fedora
- doc/examples/ubuntu-with-base-image
Fix architecture key in examples.
> examples: arch -> architecture

- shared/net.go
> shared/net: Fix hash matching

- sources/centos-http.go
> centos: Fix AltArch

- doc/examples/alpine
- doc/examples/centos
- doc/examples/debian
- doc/examples/debian-cloud-init
- doc/examples/ubuntu
- doc/examples/ubuntu-with-base-image
> doc: Sync examples with lxc-ci definitions

- managers/pacman.go
- shared/definition.go
- shared/osarch.go
- sources/archlinux-http.go
> Support Arch Linux ARM

- doc/examples/debian-cloud-init
> doc: Fix debian-cloud-init example

- doc/examples/oraclelinux
- shared/definition.go
- sources/oraclelinux-http.go
- sources/source.go
> Support Oracle Linux

- sources/oraclelinux-http.go
> sources: Fix Oracle Linux 6

- doc/examples/opensuse
- managers/manager.go
- managers/zypper.go
- shared/definition.go
- shared/util.go
- sources/opensuse-http.go
- sources/source.go
> Add openSUSE

- sources/opensuse-http.go
> sources: Use correct openSUSE tarball

- sources/opensuse-http.go
> sources: Fix openSUSE Leap 15 tarball URL

- sources/archlinux-http.go
- sources/archlinux-http_test.go
> sources: Get latest release from mirror

- sources/archlinux-http.go
The `latest/` path is not available on all Arch Linux mirrors.
Therefore, releases are determined by checking all paths.
> sources: Fix latest Arch Linux release

- distrobuilder/chroot.go
> chroot: Honor package set order for install/remove

- distrobuilder/chroot.go
> chroot: Special case openSUSE 15.x

- distrobuilder/chroot.go
> sources: Fix openSUSE --allow-downgrade flag

- managers/zypper.go
This implements the ability to add a `zypper` repository.
> Ability to add a Zypper repository

- shared/definition.go
- shared/osarch.go
> altLinux: Add architecture map

- shared/osarch.go
> altlinux: Fix typo

- shared/osarch.go
> AltLinux: Complete osarch map

- sources/sabayon.go
> sources: Fix sabayon mirror issue

- shared/util.go
> gpg: Re-try key download

- shared/chroot.go
> chroot: Fix error during chroot setup

- sources/opensuse-http.go
> source: Fix openSUSE tarball name

- sources/opensuse-http.go
> sources: Fix path to openSUSE tarballs

- sources/opensuse-http.go
> sources: Use fallback openSUSE image if needed

- doc/examples/devuan
This is mostly copied from the debian example and supplemented with bits from some old devuan templates I found. Let me know if anything needs tweaked.
> Add Devuan

- doc/examples/devuan
- doc/examples/kali
- doc/examples/kali-with-core-packages
- shared/definition.go
- sources/debootstrap.go
Per discussion with @stgraber and @Re4son in #179 / #180.
> Add EarlyPackages to debootstrap source

- Makefile
- data/ubuntu-core/init
- doc/examples/ubuntu-core
- sources/ubuntu-http.go
- sources/ubuntu-http_test.go
Support for Ubuntu Core 18 depends on https://github.com/lxc/lxc-ci/pull/42
This resolves #137
> Support Ubuntu Core

- README.md
> doc: add git to prerequisite packages

- sources/ubuntu-http.go
> sources: Use fdisk instead of kpartx

- shared/util.go
> shared: Improve GPG handling

- data/ubuntu-core/init
> ubuntu-core: Only symlink existing seeded snaps

- shared/util.go
> shared: Support armored GPG keys

- image/lxd.go
> image: Tweak squashfs options

- doc/examples/voidlinux
- doc/examples/voidlinux-musl
- managers/manager.go
- managers/xbps.go
- shared/definition.go
- shared/osarch.go
- sources/source.go
- sources/voidlinux-http.go
> Add Void Linux

- doc/examples/funtoo
- managers/egoportage.go
- managers/manager.go
- shared/definition.go
- shared/osarch.go
- sources/funtoo-http.go
- sources/source.go
Signed-off-by: Moritz Maxeiner <mm@ucw.sh>
> Add Funtoo

- distrobuilder/main.go
> Fix wiping of cache

- shared/chroot.go
> shared: Wipe rootfs/dev

- generators/cloud-init.go
> generators: Disable cloud-init for LXC in upstart

- distrobuilder/chroot.go
- distrobuilder/chroot_test.go
> distrobuilder: Optimize package handling

- distrobuilder/chroot.go
- distrobuilder/main.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- shared/definition.go
> distrobuilder: Add variants for packages and files

- sources/ubuntu-http.go
> sources: Fix Ubuntu variant check

- distrobuilder/main_build-dir.go
- shared/definition.go
> Add filters for various actions

- distrobuilder/main_lxc.go
- generators/generators_test.go
- image/lxd.go
- shared/chroot.go
- shared/util_test.go
- sources/fedora-http.go
- sources/ubuntu-http.go
> *: Various cleanups

- shared/definition.go
- shared/definition_test.go
> shared: Fix filters

- distrobuilder/main.go
- shared/chroot.go
> *: Handle SIGINT

- .snapcraft.yaml
> Add .snapcraft.yaml

- sources/ubuntu-http.go
> sources: Fix copying libs in Ubuntu Core

- distrobuilder/chroot.go
- shared/definition.go
> *: Add filters to package repositories

- mkdocs.yml
> doc: Add configuration for readthedocs

- doc/examples/ubuntu-core
Signed-off-by: Steven Trabert <tsteven4@gmail.com>
This is analogous to https://github.com/lxc/lxc-ci/commit/866b97f96b02f48dd07b0a7912ed7147dc295f44
> doc: Use source.variant for Ubuntu Core

- sources/openwrt-http.go
- sources/openwrt-http_test.go
> sources: Detect service releases for OpenWrt

- sources/openwrt-http.go
> sources: Fix OpenWrt env value

- shared/net.go
- shared/util.go
- sources/centos-http.go
This fixes some issues with the CentOS raw images.
> CentOS fixes

- sources/centos-http.go
> sources: Support CentOS DVD

- sources/centos-http.go
> sources: Fix CentOS checksum file

- doc/index.md
> doc: Mention creating a container with LXC

- doc/examples/scheme.yaml
> doc: Add schema.yaml

- distrobuilder/main.go
- shared/version/version.go
> Add version

- sources/centos-http.go
> sources/centos: Support boot iso image

- Makefile
> Makefile: Add dist target

- sources/oraclelinux-http.go
> sources/oracle: Add support for Oracle Linux 8

- sources/oraclelinux-http.go
> sources/oracle: Fix Oracle Linux 8

- sources/openwrt-http.go
> sources: Fix type in OpenWrt build

- managers/apk.go
> managers/apk: Add repo handler

- sources/centos-http.go
This adds support for CentOS Stream.
> sources: Support CentOS Stream

- sources/centos-http.go
> sources/centos: Fix filename regexes

- doc/index.md
Signed-off-by: David Sharnoff <github@dave.sharnoff.org>
> Fix example command in index.md

- doc/index.md
Signed-off-by: David Sharnoff <github@dave.sharnoff.org>
> Update index.md - separate LXD and LXC examples

- distrobuilder/chroot.go
- distrobuilder/main.go
- distrobuilder/main_build-dir.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- doc/examples/scheme.yaml
- doc/targets.md
- generators/cloud-init.go
- generators/cloud-init_test.go
- generators/dump.go
- generators/dump_test.go
- generators/generators.go
- generators/hostname.go
- generators/hostname_test.go
- generators/hosts.go
- generators/hosts_test.go
- generators/remove.go
- generators/template.go
- generators/template_test.go
- generators/upstart_tty.go
- shared/chroot.go
- shared/definition.go
- shared/definition_test.go
- sources/alpine-http.go
- sources/centos-http.go
- sources/oraclelinux-http.go
- sources/ubuntu-http.go
This PR contains changes in preparation for VM support.
> VM preparations

- distrobuilder/vm.go
- shared/definition.go
> vm: Make VM size uint64

- distrobuilder/main_lxd.go
This ensures that the VM directory and loop device are unmounted before
creating the image.
> vm: Ensure loop device is unmounted before creating image

- managers/pacman.go
Instead of completely removing /var/cache/pacman/pkg, we should only
remove its content.
Due to packages now being processed twice when running pack-lxc or
pack-lxd, the old behaviour caused pacman to fail when trying to install
new packages.
> managers/pacman: Clean up properly

- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- shared/net.go
- shared/util.go
- sources/centos-http.go
> *: Use errors.Wrap() when possible

- distrobuilder/main_lxd.go
> main: Check VM dependencies

- distrobuilder/vm.go
> vm: Handle loop partitions inside containers

- distrobuilder/main_lxd.go
> main: Add more VM dependencies

- shared/chroot.go
> shared: Close created files

- shared/chroot.go
> chroot: Unmount /dev/fuse

- shared/chroot.go
> chroot: Fix mode for special files in /dev

- shared/chroot.go
> chroot: Remove obsolete code

- distrobuilder/chroot.go
This changes the behaviour of package refresh. It only runs if packages
need to be installed or removed, or an update needs to be performed.
> chroot: Perform package refresh only when needed

- generators/lxd-agent.go
> generators/lxd-agent: Fix openRC service file

- sources/opensuse-http.go
This changes the image verification. The checksum file no longer
contains GPG content but only the sha256 checksum.
> sources/opensuse: Fix openSUSE

- sources/opensuse-http.go
> sources/opensuse: Fix verification

- data/ubuntu-core/init
> data: Fix core16 initrd

- generators/lxd-agent.go
> generators/lxd-agent: Fix running order

- generators/lxd-agent.go
> lxd-agent: Restart on failure

- generators/lxd-agent.go
See https://github.com/lxc/lxd/pull/7112
Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>
> generators/lxd-agent: Fixes ordering issue with lxd-agent

- managers/apt.go
This adds support for custom repo keys. If the full public key is
provided, it just gets imported by `apt-key`. If the key ID is provided,
gpg retrieves the public key before passing it to `apt-key`. In order
for the latter to succeed, gpg needs to be installed early.
This fixes #315 
> managers/apt: Handle repo keys

- sources/openwrt-http.go
> sources/openwrt: Fix snapshot release

- shared/chroot.go
> shared/chroot: Fix /dev/shm file mode

- generators/cloud-init.go
- generators/cloud-init_test.go
> cloud-init: Update for virtual machines

- doc/examples/scheme.yaml
- doc/generators.md
- generators/dump.go
- generators/utils.go
- shared/definition.go
This allows changing the mode, gid and uid when using the dump generator.
> generators/dump: Allow changing mode, gid and uid

- shared/util.go
> shared/util: Fix locale when importing GPG keys

- doc/examples/ubuntu.yaml
> doc/examples: Update Ubuntu example

- managers/luet.go
- managers/manager.go
- shared/definition.go
Luet is the new PMS of Sabayon Linux and of [Mocaccino OS](https://github.com/mocaccinoOS/) (not yet officially released)
> managers: Add luet pms

- doc/index.md
Updated doc/index.md.
Signed-off-by: Simos Xenitellis <simos@users.noreply.github.com>
> Updated doc/index.md

- doc/generators.md
Looks like an error in documentation.
Signed-off-by: Maksim Kaut <maksimkaut92@gmail.com>
> generators: update doc

- .github/workflows/test.yml
> github: Align workflow with LXD

- generators/lxd-agent.go
> generators: Refresh lxd-agent systemd units

- shared/util.go
It seems to me like changing the interpreter with shebang is supposed to be supported ([example](https://distrobuilder.readthedocs.io/en/latest/actions/)), but that does not appear to be the case.
I attempted to build [this project](https://github.com/engineer-man/piston) which requires that bash is used [here](https://github.com/engineer-man/piston/blob/master/container/install_script.sh#L1) (that script is inserted into [this](https://github.com/engineer-man/piston/blob/master/container/piston.yaml) file). I have no idea how other people have got this working and I may very well be barking up the wrong tree, but these changes seem to get the job done for me. Feel free to decline this PR if I'm wrong!
Keep in mind that I'm **NOT** that familiar with the go language, so if you decide to …
> Added support for changing interpreter with shebang in RunScript

- sources/centos-http.go
- sources/oraclelinux-http.go
- sources/ubuntu-http.go
> Fix bad calls to RunScript

- sources/oraclelinux-http.go
> oracle: Symlink /bin to /usr/bin if missing

- distrobuilder/chroot.go
- distrobuilder/main.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- distrobuilder/main_repack-windows.go
- shared/logger.go
> Add proper logging

- distrobuilder/main_repack-windows.go
> Ensure cleanup

- shared/definition.go
- sources/almalinux-http.go
- sources/source.go
Added AlmaLinux build definition and process.
> Add AlmaLinux Support!

- distrobuilder/chroot.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
> main: Skip overlay on xfs

- distrobuilder/main.go
> systemd: Refactor generator

- distrobuilder/main.go
> systemd-generator: Some small fixes

- distrobuilder/main.go
> main: Add fix for systemd-udev-trigger.service

- distrobuilder/main.go
> systemd: Mask more units

- distrobuilder/main.go
> main: Add fix for systemd-sysctl

- distrobuilder/main.go
> main: Replace Sanity Checks with Quick Checks

- distrobuilder/main.go
- sources/almalinux-http.go
- sources/alpine-http.go
- sources/alt-http.go
- sources/apertis-http.go
- sources/apertis-http_test.go
- sources/archlinux-http.go
- sources/archlinux-http_test.go
- sources/centos-http.go
- sources/common.go
- sources/debootstrap.go
- sources/docker.go
- sources/fedora-http.go
- sources/funtoo-http.go
- sources/gentoo.go
- sources/opensuse-http.go
- sources/openwrt-http.go
- sources/openwrt-http_test.go
- sources/oraclelinux-http.go
- sources/plamolinux-http.go
- sources/rocky-http.go
- sources/rootfs-http.go
- sources/sabayon.go
- sources/source.go
- sources/springdalelinux-http.go
- sources/ubuntu-http.go
- sources/voidlinux-http.go
> sources: Rework downloader

- sources/source.go
> sources: s/docker/docker-http/

- distrobuilder/main.go
> systemd: Mask systemd-pstore.service

- sources/centos-http.go
> sources/centos: Support CentOS 8 on armhf

- sources/oraclelinux-http.go
> sources/oracle: Fix ISO paths and support aarch64

- distrobuilder/main.go
> main: Mask ua-messaging.service

- sources/almalinux-http.go
- sources/centos-http.go
- sources/oraclelinux-http.go
- sources/rhel-common.go
- sources/rocky-http.go
- sources/springdalelinux-http.go
This removes duplicate code for RHEL bases distros.
> sources: Remove duplicate code

- sources/oraclelinux-http.go
> sources/oracle: Run yum with --skip-broken

- sources/oraclelinux-http.go
- Revert "sources/oracle: Run yum with --skip-broken"
- sources/oracle: Fix iso script
> sources/oracle: Fix aarch64 build

- sources/oraclelinux-http.go
> sources/oracle: Fix OL7 base URL

- sources/centos-http.go
> sources/centos: Check repo before disabling it

- sources/centos-http.go
> sources/centos: Include more gpg keys

- distrobuilder/main.go
> systemd: Mask hwdb-update

- sources/gentoo.go
> sources/gentoo: Support arm64 and more flavors

- distrobuilder/main.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- distrobuilder/main_repack-windows.go
- main: Clean up properly on timeout/interrupt
- main: Write to stderr if GetLogger fails
- main: Extend logging
> Improve cleanup

- distrobuilder/main_build-dir.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- generators/cloud-init.go
- generators/cloud-init_test.go
- generators/common.go
- generators/copy.go
- generators/copy_test.go
- generators/dump.go
- generators/dump_test.go
- generators/fstab.go
- generators/generators.go
- generators/generators_test.go
- generators/hostname.go
- generators/hostname_test.go
- generators/hosts.go
- generators/hosts_test.go
- generators/lxd-agent.go
- generators/remove.go
- generators/template.go
- generators/template_test.go
- generators: Refactor generators
- main: Use refactored generators
- main: Check filter before loading generator
> Refactor generators

- distrobuilder/main.go
> main: Add NoNewPrivileges=no to systemd-generator

- sources/gentoo.go
> sources: Fix gentoo regexes

- sources/gentoo.go
> sources: Fix gentoo source variant check

- distrobuilder/main.go
- sources/common.go
- sources/openwrt-http.go
- sources/oraclelinux-http.go
- sources/rhel-common.go
- sources/source.go
- sources/ubuntu-http.go
- sources: Pass cache directory
- sources: Replace TempDir with cacheDir
> Use cache directory in sources

- sources/rhel-common.go
> sources: Fix unmount for rhel based distros

- shared/definition.go
- sources/busybox.go
- sources/source.go
> sources: Add busybox

- sources/archlinux-http_test.go
> archlinux: Switch test to official mirror

- distrobuilder/main.go
> systemd: Add systemd-sysusers workaround

- sources/openwrt-http.go
> sources/openwrt: Fix directory name

- sources/rhel-common.go
- sources/centos: Fix error message
- sources/centos: Unmount raw file
> Fix CentOS raw image

- distrobuilder/vm.go
- vm: Check existance of loop device before detaching it
- vm: Fix error message
> vm: Fix unmount

- sources/busybox.go
> sources/busybox: Fix mkdir call

- distrobuilder/chroot.go
- distrobuilder/main.go
- distrobuilder/main_build-dir.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- sources/almalinux-http.go
- sources/alpine-http.go
- sources/alt-http.go
- sources/apertis-http.go
- sources/archlinux-http.go
- sources/busybox.go
- sources/centos-http.go
- sources/fedora-http.go
- sources/funtoo-http.go
- sources/gentoo.go
- sources/opensuse-http.go
- sources/openwrt-http.go
- sources/oraclelinux-http.go
- sources/rhel-common.go
- sources/rocky-http.go
- sources/rootfs-http.go
- sources/sabayon.go
- sources/springdalelinux-http.go
- sources/ubuntu-http.go
- sources/voidlinux-http.go
- main: Add logging
- sources: Add logging
- main: Wrap overlay errors
> Add more logging

- distrobuilder/main.go
- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
- image/lxc.go
- image/lxc_test.go
- image/lxd.go
- image/lxd_test.go
- shared/util.go
- image: Fix LXD compression
- image: Add compression flag for lxc images
- image: Update tests
- shared: Add zstd compression
- main: Add type and compression to help message
> Update compression code

- Makefile
> Makefile: Tweak generation of dist tarball

- sources/plamolinux-http.go
pkgtool, that is package manager for plamo, has been updated. The
package name is changed to pkgtools8, and change installation process
to match pkgtools8.
Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>
> sources/plamolinux: Support new pkgtools8

- distrobuilder/main.go
> systemd: Properly check for instance type

- distrobuilder/main_repack-windows.go
- distrobuilder/main_repack-windows_test.go
> windows: Add Windows 11 support

- distrobuilder/main.go
- distrobuilder/main_lxd.go
- shared/util.go
- sources/oraclelinux-http.go
- sources/rhel-common.go
- sources/ubuntu-http.go
> *: Replace RunCommand with RsyncLocal

- shared/util.go
> utils: Fix error handling in RsyncLocal

- distrobuilder/main_repack-windows.go
> main: Add support for Windows Server 2022

- sources/openwrt-http.go
This drops the use of the lxd-openwrt repo which doesn't seem to be
needed. Dropping this repo also removes the SDK requirement.
> sources/openwrt: Drop lxd-openwrt repo and SDK

- distrobuilder/main_lxc.go
- distrobuilder/main_lxd.go
> main: Log image creation

- sources/gentoo.go
> sources/gentoo: Allow custom source variants

- generators/cloud-init.go
- generators/cloud-init_test.go
- generators: Fix cloud-init network config
- generators: Add trailing newline to cloud-init files
> cloud-init fixes

- .github/workflows/test.yml
> .github/workflows: Drop Go 1.13

- sources/common.go
> sources: Fix downloads with multiple hashes

- distrobuilder/main.go
> systemd: Use absolute path to udevadm

- generators/cloud-init.go
This fixes a bug where a provided content would be hard-coded in the
template, not allowing users to customize the cloud-init config.
Any provided content will now be used as the new default value.
> generators/cloud-init: Fix content override

- sources/centos-http.go
Hi there !
CentOS 9 stream is currently not supported/generated with the actual version of distrobuilder.
I tried to edit the code of distrobuilder to be able to generate CentOS 9 stream images.
The one (container only, not a cloud version) I have generated seems to work correctly (used in a CI).
I was able to generate a VM version but didn't check it.
I made a PR to also edit the lxc-ci repository.
Resolves #598.
Signed-off-by: Sébastien BOUTON  <s.boutontitandc.fr>
> Add centos 9 stream

- shared/definition_test.go
> test: Add TestDefinitionFilterTypeUnmarshalYAML

- distrobuilder/main.go
> main: systemd's ReadWritePaths came with version 231

- distrobuilder/main.go
This reintroduces one of the NetworkManager workarounds which was
removed in #633. Without the workaround, some containers only get an
IPv4 address after a container reboot.
> main: Reintroduce NetworkManager workaround

- distrobuilder/main.go
> main: Mask systemd-firstboot.service

- sources/alpine-http.go
In the past, distrobuilder would always download the .0 release if
image.release was provided as `<major>.<minor>`.
This changes the behaviour to instead always downloads the latest point
release.
> sources/alpine: Always download latest point release

- sources/oraclelinux-http.go
If no updates can be found using HTTP body parsing, try finding updates
through iteration.
> sources/oracle: Find updates through iteration

- doc/image.md
- doc/source.md
- Add output note to image.md
- Add rootfs-http to downloaders list
> Minor docs suggestions

- doc/source.md
- shared/definition.go
- sources/openeuler-http.go
- sources/source.go
Signed-off-by: Li Chaoran <pkwarcraft@gmail.com>
> source: add support for openeuler downloader

- shared/definition.go
- sources/source.go
- sources/vyos-http.go
> sources: Add VyOS

- distrobuilder/main_repack-windows.go
- distrobuilder/vm.go
- sources/oraclelinux-http.go
- sources/rhel-common.go
- sources/vyos-http.go
> *: Set fstype when mounting

- README.md
> Fix troubleshoot link

- sources/openwrt-http.go
> Add OpenWRT 23.05

- sources/rpmbootstrap.go
Ubuntu distribution provides dnf package to replace yum package since release 21.04. So we add dnf support in rmpbootstrap to support building rpm distribution on ubuntu.
> Support dnf in rpmbootstrap

- sources/nixos-http.go
Support NixOS stable releases
Part of https://github.com/lxc/lxc-ci/issues/786
> nixos-http: support versioned releases

- README.md
Installing requires the make package.
Also a readability change.
> Update README.md Install Instructions

- distrobuilder/main_repack-windows.go
- generators/template.go
- go.mod
- go.sum
- shared/util.go
- shared/util_test.go
> Bump pongo2 to v4

- sources/debootstrap.go
https://bugs.launchpad.net/ubuntu/+source/base-files/+bug/2054925
> debootstrap: Pass --no-merged-usr on noble

- sources/debootstrap.go
Based on https://github.com/lxc/distrobuilder/issues/825
> Debian sid use --no-merged-usr

- doc/examples/ubuntu.yaml
> Updated ubuntu example to use ROOTFS_DEVICE_UUID

- distrobuilder/main_repack-windows.go
- shared/util.go
And make genisoimage progress output better
> Clean up iso mount gen warnings

- distrobuilder/main_repack-windows.go
- shared/util.go
- shared/util_test.go
And fixes potenial bug if sources directory not found
> Refactor find boot.wim and install.wim logic

- distrobuilder/main_repack-windows.go
> Repack windows bios boot support

- distrobuilder/vm.go
The parse failure occurred occasionally, sometime deviceNumbers[1] is empty, so cause the parse failure.
The fix trim space output first then split and refact the parse logic.
> Fixed device major minor parse failure

- sources/nixos-http.go
Waiting on https://github.com/NixOS/nixpkgs/pull/335366 and then a few more days for the build artifacts to be published.
> nixos-http: use incus-specific image for unstable

- distrobuilder/main_repack-windows.go
cf. #881 , a quick pr, can be improved
> Add mkisofs support

- doc/examples/ubuntu.yaml
* Add Noble, Oracular, and Plucky releases
* Remove obsolete releases Groovy, Hirsute, Impish
> ubuntu.yaml: add Noble, Oracular, Plucky

- sources/nixos-http.go
> remove nixos 24.05 logic

- distrobuilder/lxc.generator
> lxc.generator Fixed typo in comments

- sources/openwrt-http.go
good evening,
This is my local patch to fix #932. It turns on gpg signature verification by default, regardless of the transport used, except when `skip_verification: true` is used. This was my first go at Go, so ymmv :-)
To avoid breaking CI, the gpg keys needed to be refreshed. That's https://github.com/lxc/lxc-ci/pull/903.
> openwrt: verify checksum and signature by default (fixes: #932)

- sources/fedora-http.go
> fedora-http: Use RsyncLocal
